# Generated by Django 4.2.7 on 2023-12-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_product_wishlist_collectable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='collectable',
            new_name='product',
        ),
    ]
