# Generated by Django 4.2.7 on 2023-12-03 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_collectable_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
