# Generated by Django 4.2.7 on 2023-12-04 00:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellCollectable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectable_item', models.CharField(max_length=250)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=250)),
                ('contact_number', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.platform')),
            ],
        ),
    ]
